AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'coverage/**/*'

# Metrics configuration for complex business logic
Metrics/MethodLength:
  Max: 50
  Exclude:
    - 'spec/**/*'
    - 'lib/integrations/linear.rb' # Complex GraphQL queries
    - 'lib/task_manager.rb' # Database setup

Metrics/ClassLength:
  Max: 500
  Exclude:
    - 'spec/**/*'
    - 'lib/task_intelligence.rb' # Complex AI logic
    - 'lib/integrations/linear.rb' # Comprehensive Linear integration
    - 'lib/task_manager.rb' # Core business logic

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 45
  Exclude:
    - 'spec/**/*'
    - 'lib/task_intelligence.rb' # Complex calculations

Metrics/CyclomaticComplexity:
  Max: 18
  Exclude:
    - 'spec/**/*'
    - 'lib/task_intelligence.rb' # Complex decision trees

Metrics/PerceivedComplexity:
  Max: 18
  Exclude:
    - 'spec/**/*'
    - 'lib/task_intelligence.rb' # Complex business rules

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
    - 'Rakefile'
    - '**/*.rake'

# Style preferences
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19

# Layout preferences
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Naming conventions
Naming/PredicateName:
  ForbiddenPrefixes:
    - is_

# Lint rules
Lint/DuplicateBranch:
  Enabled: false

# Style rules
Style/GlobalVars:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false